version: '3.1'

services:
    node:
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
          - '3000:3000'
      volumes: 
        - .:/app/mern-docker-app
    
    mongo:
      image: mongo:latest
      ports: 
        - '27017:27017'
      volumes:
          - ~/mongo-db-docker-data:/data/db